services:
  bluff-pub-frontend:
    build:
      context: .
      args:
        VITE_SOCKET_URL: ""
    container_name: bluff-pub-frontend
    restart: unless-stopped
    environment:
      PORT: 3000
    networks:
      - app_network

networks:
  app_network:
    external: true
